In [1]:
#Import Dependencies
import pandas as pd
import os
import csv

In [2]:
#Load data sets
MW2017= pd.read_csv("Monarch_Watch_2017.csv")
MW2018= pd.read_csv("Monarch_Watch_2018.csv")
MW2019= pd.read_csv("Monarch_Watch_2019.csv")
MW2020= pd.read_csv("Monarch_Watch_2020.csv")

In [5]:
MW2020DROP= MW2020.drop(columns=['Notes'])

In [7]:
MW2020DROP

,Tag Code,Date,City/Location,State/Province,ZIP/PC,Country,First Name
0,AABX630,10/22/2020,North Cape May,NJ,8204,USA,Mark
1,AABX693,9/30/2020,Sewell,NJ,8080,USA,Debbie
2,AAHL099,9/26/2020,Saint-Lambert,QC,J4p 2j4,CAN,Luce
3,AAHL209,10/10/2020,Quebec City,QC,G1S 3J3,CAN,Pierre
4,AAJM336,8/26/2020,Wilmington,NC,28403,USA,Franca
...,...,...,...,...,...,...,...
872,YEB316,10/13/2020,Hillsborough,NC,27278,USA,Jason
873,ZCU167,9/26/2020,Livonia,MI,48154,USA,Jessica
874,ZCU176,8/30/2020,Harrison township,MI,48045,USA,Daniel
875,ZCU183,9/4/2020,Baltimore,MI,48047,USA,David
876,ZCU197,8/31/2020,Milford,MI,48357,USA,Roman